### ISSUE TITLE
0.15.1: build fails with `implicit declaration of function ‘s2n_cleanup_final’`

### ISSUE THREAD

**Issue by kloczek** [awslabs/aws-c-io#688]
### Describe the bug

Build fails with `implicit declaration of function ‘s2n_cleanup_final’`.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Build shuld not fail.

### Current Behavior

```console
/usr/bin/gcc -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_IO_EXPORTS -DAWS_IO_USE_IMPORT_EXPORT -DAWS_USE_EPOLL -DHAVE_SYSCONF -DINTEL_NO_ITTNOTIFY_API -DUSE_S2N -Daws_c
_io_EXPORTS -I/home/tkloczko/rpmbuild/BUILD/aws-c-io-0.15.1/include -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -g -grecord-gcc-switches -p
ipe -mtls-dialect=gnu2 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fdata-sections -ffunction-sections -fstack-protector-strong -specs
=/usr/lib/rpm/redhat/redhat-hardened-cc1 -flto=auto -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Werror=format-security -O2 -g -DNDEBUG -std=gnu99 -fPIC -fvisi
bility=hidden -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wextra -pedantic -Wno-long-long -fPIC -MD -MT CMakeFiles/aws-c-io.dir/source/tls_channel_handler.c.o -MF CMakeFiles/aws-c-io
.dir/source/tls_channel_handler.c.o.d -o CMakeFiles/aws-c-io.dir/source/tls_channel_handler.c.o -c /home/tkloczko/rpmbuild/BUILD/aws-c-io-0.15.1/source/tls_channel_handler.c
/home/tkloczko/rpmbuild/BUILD/aws-c-io-0.15.1/source/s2n/s2n_tls_channel_handler.c: In function ‘aws_tls_clean_up_static_state’:
/home/tkloczko/rpmbuild/BUILD/aws-c-io-0.15.1/source/s2n/s2n_tls_channel_handler.c:258:9: error: implicit declaration of function ‘s2n_cleanup_final’; did you mean ‘s2n_cleanup_thread’? [-W
implicit-function-declaration]
  258 |         s2n_cleanup_final();
      |         ^~~~~~~~~~~~~~~~~
      |         s2n_cleanup_thread
gmake[2]: *** [CMakeFiles/aws-c-io.dir/build.make:345: CMakeFiles/aws-c-io.dir/source/s2n/s2n_tls_channel_handler.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
```
s2n-tls 1.5.6.

### Reproduction Steps

Try to build with s2n-tls 1.5.6.

### aws-c-io version used

0.15.1

### Compiler and version used

gcc 14

### Operating System and version

Linux x86/64
```[tasklist]
### Tasks
```

**Comment by graebm** [comment]
`s2n_cleanup_final` was added recently to s2n-tls very recently: https://github.com/aws/s2n-tls/commit/9819ac0e2e028e3b761855fc4f2f8134008d3f4b. You can use that specific commit of s2n-tls, or their `main` branch, until they make another release (likely within a week). Or you can hold back updating aws-c-io to 

Sorry, this was a case of bad timing. The s2n-tls team asked us to use this function, and we didn't realize it wasn't available yet in a tagged release (aws-c-io's tests build against the main branch of s2n-tls). I've asked the s2n-tls team to do their next release ASAP, but I don't know what rigamarole they might go through before each release.

I'll post more when I have updates...

**Comment by kloczek** [comment]
Don't worry about me. I can wait until next release 😄 
Thank you for confirmation that it is real issue 👍

**Comment by graebm** [comment]
Ok, fix if you use the latest S2N-TLS release: [v1.5.7](https://github.com/aws/s2n-tls/releases/tag/v1.5.7)

**Comment by kloczek** [comment]
Just tested and all looks good now 👍 
Thank you.
